listen_addresses = '*'

max_connections = 1000
shared_buffers = 16GB
effective_cache_size = 48GB
maintenance_work_mem = 2GB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 4194kB
huge_pages = try
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 40
max_parallel_workers_per_gather = 4
max_parallel_workers = 40
max_parallel_maintenance_workers = 4

# Configurações do pg_stat_statements
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
pg_stat_statements.max = 10000
pg_stat_statements.track_utility = on
pg_stat_statements.track_planning = on  # Disponível no PostgreSQL 14+
track_io_timing = on  # Habilita o monitoramento de timings de I/O

# Configurações de log (opcional, mas útil para monitoramento)
log_statement = 'none'
log_duration = off
log_min_duration_statement = 1000  # Registra consultas que demoram mais de 1s